/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperExportManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
import proje.java.sql.MysqlConn;
import proje.staj.db.Devam;
import proje.staj.db.Staj;
import proje.staj.managers.DevamManager;
import proje.staj.managers.StajManager;
import proje.staj.utils.DevamTableModel;

/**
 *
 * @author Zeynepnida
 */
public class DevamDurum extends javax.swing.JPanel {

    /**
     * Creates new form DevamDurum
     */
     private Devam selectedDevam;
    private Staj selectedStaj;
    public DevamDurum() throws SQLException {
        initComponents();

        //  ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/arama.png")));
        ArrayList<Devam> devamListem = new ArrayList<Devam>();
        DevamTableModel dtm = new DevamTableModel(new ArrayList());
        dtm.setColumnIdentifiers(new Object[]{"STAJ ID", "TARİH", "DEVAM"});
        jTable1.setModel(dtm);
        ((DefaultComboBoxModel) this.cmbOgrenci.getModel()).removeAllElements();
        ArrayList<Staj> stajList = new StajManager().getAllOgrenci();
        for (Staj staj : stajList) {
            ((DefaultComboBoxModel) this.cmbOgrenci.getModel()).addElement(staj);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbOgrenci = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cmbOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOgrenciActionPerformed(evt);
            }
        });

        jLabel1.setText("Öğrenci :");

        jButton1.setText("PDF YAZDIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(cmbOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jButton1)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOgrenciActionPerformed

        if (this.cmbOgrenci.getSelectedItem() != null
                && this.cmbOgrenci.getSelectedItem() instanceof Staj) {
            try {
                this.selectedStaj = (Staj) this.cmbOgrenci.getSelectedItem();
                ((DevamTableModel) this.jTable1.getModel()).setStaj(selectedStaj);
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(DevamDurum.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbOgrenciActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /*  try {
            String pdfFileName = "D:/C4_report.pdf";
            String jrxmlFileName = getClass().getResource("/report/devam.jrxml").getFile();
            JasperReport jr=JasperCompileManager.compileReport(jrxmlFileName);
          HashMap   parameters = new HashMap();
          String whereCase="";
        if(this.selectedStaj!=null)  
          whereCase+=" and d.Staj_ID="+this.selectedStaj.getId();
           
           
          
          parameters.put("whereCase", whereCase);
           JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(jr, parameters, MysqlConn.getConnection().getConn());
            JasperExportManager.exportReportToPdfFile(jprint, pdfFileName);
            
                File myFile = new File( pdfFileName); // ekranada gosterme
                Desktop.getDesktop().open(myFile);
            

        } catch (JRException ex) {
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        }   
        */

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOgrenci;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
