/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import com.mysql.jdbc.MySQLConnection;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

import proje.java.sql.MysqlConn;
import proje.staj.db.Bolum;
import proje.staj.db.Ogrenci;
import proje.staj.db.Universite;
import proje.staj.managers.BolumManager;
import proje.staj.managers.OgrenciManager;
import proje.staj.managers.UniversiteManager;
import proje.staj.utils.OgrenciTableModel;

/**
 *
 * @author Zeynepnida
 */
public class OgrenciDuzenle extends javax.swing.JPanel {

    /**
     * Creates new form OgrenciDuzenle
     */
    private Ogrenci selectedOgrenci;

    public OgrenciDuzenle() {
        try {
            initComponents();

            ArrayList<Ogrenci> ogrenciListem = new ArrayList<Ogrenci>();
            OgrenciTableModel dtm = new OgrenciTableModel(new OgrenciManager().getAllOgrenci());
            dtm.setColumnIdentifiers(new Object[]{"TC", "İSİM", "SOYİSİM", "ÜNİVERSİTE", "BÖLÜM", "BAŞLAMA TARİHİ", "BİTİŞ TARİHİ", "STAJ GÜNÜ", "PROJE", "BİRİM"});
            table.setModel(dtm);

            UniversiteManager uniMan = new UniversiteManager();
            ArrayList<Universite> uniList = uniMan.getAllUni();
            for (Universite uni : uniList) {
                ((DefaultComboBoxModel) this.cmbOkul.getModel()).addElement(uni);
            }

            ((DefaultComboBoxModel) this.cmbBolum.getModel()).removeAllElements();
            BolumManager bolMan = new BolumManager();
            ArrayList<Bolum> bolList = bolMan.getAllBolum();
            for (Bolum bol : bolList) {
                ((DefaultComboBoxModel) this.cmbBolum.getModel()).addElement(bol);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adText = new javax.swing.JTextField();
        tcText = new javax.swing.JTextField();
        soyadText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbOkul = new javax.swing.JComboBox<>();
        cmbBolum = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Duzenle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(adText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 320, -1));
        add(tcText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 320, -1));
        add(soyadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 320, -1));

        jLabel1.setText("TC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 167, -1));

        jLabel2.setText("AD");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 167, -1));

        jLabel4.setText("OKUL");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 167, -1));

        jLabel5.setText("BOLUM");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 167, 20));

        jLabel3.setText("SOYAD");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 167, -1));
        add(cmbOkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 320, -1));
        add(cmbBolum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 320, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 1120, 360));

        Duzenle.setText("DÜZENLE");
        Duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuzenleActionPerformed(evt);
            }
        });
        add(Duzenle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 140, 60));

        jButton1.setText("PDF YAZDIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 130, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void DuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuzenleActionPerformed

        String TC = tcText.getText();
        String ad = adText.getText();
        String soyad = soyadText.getText();
        Universite universite = (Universite) cmbOkul.getSelectedItem();
        Bolum bolum = (Bolum) cmbBolum.getSelectedItem();
        try {

            this.selectedOgrenci.setTc(Long.parseLong(TC));
            this.selectedOgrenci.setAd(ad);
            this.selectedOgrenci.setSoyad(soyad);
            this.selectedOgrenci.setOkul(universite);
            this.selectedOgrenci.setBolum(bolum);

            OgrenciManager ogrenciMan = new OgrenciManager();
            ogrenciMan.duzenleOgrenci(this.selectedOgrenci);
            ((OgrenciTableModel) this.table.getModel()).fireTableDataChanged();

        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_DuzenleActionPerformed

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed

        this.selectedOgrenci = ((OgrenciTableModel) this.table.getModel()).getOgrenci(table.getSelectedRow());

        tcText.setText(selectedOgrenci.getTc().toString());
        adText.setText(selectedOgrenci.getAd());
        soyadText.setText(selectedOgrenci.getSoyad());
        cmbOkul.setSelectedItem(selectedOgrenci.getOkul());
        cmbBolum.setSelectedItem(selectedOgrenci.getBolum());

        // TODO add your handling code here:
    }//GEN-LAST:event_tableMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     /*   try {
            String pdfFileName = "D:/C1_report.pdf";
            String jrxmlFileName = getClass().getResource("/report/ogrenci.jrxml").getFile();
            JasperReport jr=JasperCompileManager.compileReport(jrxmlFileName);
          HashMap   parameters = new HashMap();
          String whereCase="";
          if(this.selectedOgrenci!=null)
              whereCase+="and o.TC="+this.selectedOgrenci.getTc();
           
          
          parameters.put("whereCase", whereCase);
           JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(jr, parameters, MysqlConn.getConnection().getConn());
            JasperExportManager.exportReportToPdfFile(jprint, pdfFileName);
            
                File myFile = new File( pdfFileName); // ekranda gosterme
                Desktop.getDesktop().open(myFile);
            
// TODO add your handling code here:
        } catch (JRException ex) {
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Duzenle;
    private javax.swing.JTextField adText;
    private javax.swing.JComboBox<String> cmbBolum;
    private javax.swing.JComboBox<String> cmbOkul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField soyadText;
    private javax.swing.JTable table;
    private javax.swing.JTextField tcText;
    // End of variables declaration//GEN-END:variables
}
