/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import proje.staj.db.Proje;
import proje.staj.db.ProjeStaj;
import proje.staj.managers.AramaManager;
import proje.staj.managers.ProjeManager;
import proje.staj.utils.ProjeTableModel;

/**
 *
 * @author Zeynepnida
 */
public class ProjeAra extends javax.swing.JPanel {

    private Proje projee;
    private ProjeStaj prjstaj;
    String projeadi;

    /**
     * Creates new form projeAra
     */
    public ProjeAra() {

        initComponents();
        sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/temizle.png")));
        arama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/arama.png")));
        try {
            sil.setVisible(false);
            guncelle.setVisible(false);
            //ProjeTableModel dtm = new ProjeTableModel(new ProjeManager().getProjeListByAd());
            ProjeTableModel dtm = new ProjeTableModel(new ProjeManager().getAllOgrenci());
            dtm.setColumnIdentifiers(new Object[]{"ID", "PROJE ADI", "AÇIKLAMA"});
            this.jTable1.setModel(dtm);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        proje = new javax.swing.JTextField();
        arama = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        txtaciklama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        table.setViewportView(jTable1);

        jLabel1.setText("Proje Adı");

        arama.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeynepnida\\Desktop\\stajj\\New Folder\\proje2\\resim\\arama.png")); // NOI18N
        arama.setText("ARA");
        arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaActionPerformed(evt);
            }
        });

        sil.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zeynepnida\\Desktop\\stajj\\New Folder\\proje2\\resim\\temizle.png")); // NOI18N
        sil.setText("Sİl");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        guncelle.setText("GÜNCELLE");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        jLabel2.setText("Proje Açıklaması :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtaciklama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(proje))
                        .addGap(130, 130, 130)
                        .addComponent(arama, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(proje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(arama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaActionPerformed

        sil.setVisible(true);
        guncelle.setVisible(true);
        projeadi = proje.getText();
        ProjeManager projeMan = new ProjeManager();
        try {
            ArrayList<Proje> projeList = projeMan.getProjeListByAd(projeadi);
            if (projeList.size() > 0) {
                proje.setText("");
                txtaciklama.setText("");
            }
            ((ProjeTableModel) this.jTable1.getModel()).setList(projeList);

        } catch (SQLException ex) {
            Logger.getLogger(ProjeAra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aramaActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed

        ProjeManager projeMan = new ProjeManager();
        try {
            projeMan.silProje(this.projee);
            ((ProjeTableModel) this.jTable1.getModel()).removeProje(this.projee);
        } catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_silActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        this.projee = ((ProjeTableModel) this.jTable1.getModel()).getProje(jTable1.getSelectedRow());
        proje.setText(projee.getAdi());
        txtaciklama.setText(projee.getAciklama());
    }//GEN-LAST:event_jTable1MousePressed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed

        String aciklama = txtaciklama.getText();
        projeadi = proje.getText();
        try {
            this.projee.setAdi(projeadi);
            this.projee.setAciklama(aciklama);
            ProjeManager projeMan = new ProjeManager();
            projeMan.duzenleProje(this.projee);
            ((ProjeTableModel) this.jTable1.getModel()).fireTableDataChanged();
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guncelleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arama;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField proje;
    private javax.swing.JButton sil;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField txtaciklama;
    // End of variables declaration//GEN-END:variables

}
