/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperExportManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
import proje.java.sql.MysqlConn;
import proje.staj.db.Staj;
import proje.staj.managers.AramaManager;
import proje.staj.managers.StajManager;

/**
 *
 * @author Zeynepnida
 */
public class Rapor extends javax.swing.JPanel {

    /**
     * Creates new form Rapor
     */
    public Rapor() throws SQLException {
        initComponents();
        ((DefaultComboBoxModel) this.cmbTC.getModel()).removeAllElements();
        ArrayList<Staj> stajList = new StajManager().getAllOgrenci();
        ((DefaultComboBoxModel) this.cmbTC.getModel()).addElement(null);
        for (Staj staj : stajList) {
            ((DefaultComboBoxModel) this.cmbTC.getModel()).addElement(staj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raporTuru = new javax.swing.ButtonGroup();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_tc = new javax.swing.JLabel();
        dtBaslangic = new org.jdesktop.swingx.JXDatePicker();
        dtBitis = new org.jdesktop.swingx.JXDatePicker();
        cmbTC = new javax.swing.JComboBox<>();
        kaydet = new javax.swing.JButton();

        raporTuru.add(rb1);
        rb1.setText("Öğrenci Listesi");

        raporTuru.add(rb2);
        rb2.setText("Devam Listesi");

        raporTuru.add(rb3);
        rb3.setText("Proje Listesi ");

        jLabel3.setText("    Rapor :");

        txt_tc.setText("     Öğrenci :");

        cmbTC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTCActionPerformed(evt);
            }
        });

        kaydet.setText("GÖSTER");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(rb2)
                                    .addGap(38, 38, 38)
                                    .addComponent(rb3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbTC, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(dtBaslangic, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dtBitis, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tc))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtBaslangic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtBitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb1)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTCActionPerformed
    /*    Staj selectedStaj = new Staj();
        AramaManager aramaManager = new AramaManager();
        if (this.cmbTC.getSelectedItem() != null && this.cmbTC.getSelectedItem() instanceof Staj) {
            selectedStaj = (Staj) this.cmbTC.getSelectedItem();
        }
    }//GEN-LAST:event_cmbTCActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed

       Date baslangicTarihi = this.dtBaslangic.getDate();
        Date bitisTarihi = this.dtBitis.getDate();
        Staj selectedStaj = (Staj) this.cmbTC.getSelectedItem();
        if (this.rb1.isSelected() == true) {
            try {
                SimpleDateFormat frmFormat = new SimpleDateFormat("yyyy-MM-dd");
                String pdfFileName = "D:/C5_report.pdf";
                String jrxmlFileName = getClass().getResource("/report/RAPOR_1.jrxml").getFile();
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFileName);
                HashMap parameters = new HashMap();
                String whereCase = " and ( "
                        + " ("
                        + "     s.Baslama_tarihi < '" + frmFormat.format(baslangicTarihi) + "' "
                        + " and s.Bitis_tarihi > '" + frmFormat.format(baslangicTarihi) + "'"
                        + " )"
                        + " or s.Baslama_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " or s.Bitis_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " ) ";
                if (this.cmbTC.getSelectedItem() instanceof Staj) {
                    whereCase += " and s.ID=" + ((Staj) this.cmbTC.getSelectedItem()).getId();
                }
                parameters.put("whereCase", whereCase);
                JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(jr, parameters, MysqlConn.getConnection().getConn());
                JasperExportManager.exportReportToPdfFile(jprint, pdfFileName);
                File myFile = new File(pdfFileName); // ekranda gosterme
                Desktop.getDesktop().open(myFile);
            } catch (JRException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (this.rb2.isSelected() == true) {
            try {
                SimpleDateFormat frmFormat = new SimpleDateFormat("yyyy-MM-dd");
                String pdfFileName = "D:/C6_report.pdf";
                String jrxmlFileName = getClass().getResource("/report/RAPOR_2.jrxml").getFile();
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFileName);
                HashMap parameters = new HashMap();
                String whereCase = " and ( "
                        + " ("
                        + "     s.Baslama_tarihi < '" + frmFormat.format(baslangicTarihi) + "' "
                        + " and s.Bitis_tarihi > '" + frmFormat.format(baslangicTarihi) + "'"
                        + " )"
                        + " or s.Baslama_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " or s.Bitis_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " ) ";
                if (this.cmbTC.getSelectedItem() instanceof Staj) {
                    whereCase += " and s.ID=" + ((Staj) this.cmbTC.getSelectedItem()).getId();
                }

                parameters.put("whereCase", whereCase);
                JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(jr, parameters, MysqlConn.getConnection().getConn());
                JasperExportManager.exportReportToPdfFile(jprint, pdfFileName);

                File myFile = new File(pdfFileName); // ekranda gosterme
                Desktop.getDesktop().open(myFile);
            } catch (JRException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                SimpleDateFormat frmFormat = new SimpleDateFormat("yyyy-MM-dd");
                String pdfFileName = "D:/C7_report.pdf";
                String jrxmlFileName = getClass().getResource("/report/RAPOR_3.jrxml").getFile();
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFileName);
                HashMap parameters = new HashMap();
                String whereCase = " and ( "
                        + " ("
                        + "     s.Baslama_tarihi < '" + frmFormat.format(baslangicTarihi) + "' "
                        + " and s.Bitis_tarihi > '" + frmFormat.format(baslangicTarihi) + "'"
                        + " )"
                        + " or s.Baslama_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " or s.Bitis_tarihi between '" + frmFormat.format(baslangicTarihi) + "' and '" + frmFormat.format(bitisTarihi) + "'"
                        + " ) ";
                if (this.cmbTC.getSelectedItem() instanceof Staj) {
                    whereCase += " and s.ID=" + ((Staj) this.cmbTC.getSelectedItem()).getId();
                }
                parameters.put("whereCase", whereCase);
                JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(jr, parameters, MysqlConn.getConnection().getConn());
                JasperExportManager.exportReportToPdfFile(jprint, pdfFileName);

                File myFile = new File(pdfFileName); // ekranda gosterme
                Desktop.getDesktop().open(myFile);
            } catch (JRException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(OgrenciDuzenle.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_kaydetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTC;
    private org.jdesktop.swingx.JXDatePicker dtBaslangic;
    private org.jdesktop.swingx.JXDatePicker dtBitis;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kaydet;
    private javax.swing.ButtonGroup raporTuru;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JLabel txt_tc;
    // End of variables declaration//GEN-END:variables
}
