/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proje.staj.db.Sifre;
import proje.staj.managers.AramaManager;
import proje.staj.managers.SifreManager;

/**
 *
 * @author Zeynepnida
 */
public class SifreSifirla extends javax.swing.JPanel {

    private Sifre sifre;

    /**
     * Creates new form SifreSifirla
     */
    public SifreSifirla() {
        initComponents();
         kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/ekle.png")));
        arama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/arama.png")));
        kaydet.setVisible(false);
        pSoyad.setVisible(false);
        txtSoyadi.setVisible(false);
        txtKullanici.setVisible(false);
        kAdi.setVisible(false);
        txtsifre.setVisible(false);
        Sifre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adi = new javax.swing.JLabel();
        txtAdi = new javax.swing.JTextField();
        arama = new javax.swing.JButton();
        pSoyad = new javax.swing.JLabel();
        kAdi = new javax.swing.JLabel();
        Sifre = new javax.swing.JLabel();
        txtSoyadi = new javax.swing.JTextField();
        txtKullanici = new javax.swing.JTextField();
        txtsifre = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();

        adi.setText("Personel Adı");

        arama.setText("ARA");
        arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaActionPerformed(evt);
            }
        });

        pSoyad.setText("Personel Soyadı");

        kAdi.setText("Kullanıcı Adı");

        Sifre.setText("Şifre");

        kaydet.setText("KAYDET");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtsifre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(kAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtKullanici))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pSoyad)
                                .addGap(38, 38, 38)
                                .addComponent(txtSoyadi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addComponent(arama, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arama, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(pSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(kAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsifre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaActionPerformed

        AramaManager aramaManager = new AramaManager();
        String adi = txtAdi.getText();
        try {
            sifre = aramaManager.arasifre(adi);
            arama.setVisible(false);
           kaydet.setVisible(true);
            pSoyad.setVisible(true);
            txtSoyadi.setVisible(true);
            txtKullanici.setVisible(true);
            kAdi.setVisible(true);
            txtsifre.setVisible(true);
            Sifre.setVisible(true);

            if (sifre != null) {
                txtAdi.setText(sifre.getP_ad());
                txtSoyadi.setText(sifre.getP_soyad());
            }
        } catch (SQLException ex) {
            Logger.getLogger(SifreSifirla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aramaActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        SifreManager sifreManager = new SifreManager();
        String adi = txtAdi.getText();
        String soyadi = txtSoyadi.getText();
        String kullanici = txtKullanici.getText();
        int sifree = Integer.parseInt(txtsifre.getText());
        try {
            
            this.sifre.setP_ad(adi);
            this.sifre.setP_soyad(soyadi);
            this.sifre.setKullanici_ad(kullanici);
            this.sifre.setSifre(sifree);
             
            sifreManager.duzenlesifre(this.sifre);
        }
         catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(SifreSifirla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kaydetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sifre;
    private javax.swing.JLabel adi;
    private javax.swing.JButton arama;
    private javax.swing.JLabel kAdi;
    private javax.swing.JButton kaydet;
    private javax.swing.JLabel pSoyad;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JTextField txtKullanici;
    private javax.swing.JTextField txtSoyadi;
    private javax.swing.JTextField txtsifre;
    // End of variables declaration//GEN-END:variables
}
