package proje.staj.forms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proje.staj.db.Sifre;
import proje.staj.managers.SifreManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Zeynepnida
 */
public class SifreKaydet extends javax.swing.JPanel {

    private Sifre sifreee;

    /**
     * Creates new form sifre
     */
    public SifreKaydet() {
        initComponents();
        kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/ekle.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pAdi = new javax.swing.JTextField();
        pSoyadi = new javax.swing.JTextField();
        kullaniciadi = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        sifre = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Personel Adı");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 87, 91, 20));

        jLabel2.setText("Personel Soyadı");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 151, -1, 20));

        jLabel3.setText("Kullanıcı Adı");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 218, 91, 20));

        jLabel4.setText("Şifre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 277, 91, 20));
        add(pAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 106, 30));
        add(pSoyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 144, 106, 30));
        add(kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 211, 106, 30));

        kaydet.setText("KAYDET");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        add(kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 366, 114, 40));
        add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 272, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed

        try {

            SifreManager sifreManager = new SifreManager();
            String adi = pAdi.getText();
            String soyadi = pSoyadi.getText();
            String kullanici = kullaniciadi.getText();
            int sifree = Integer.parseInt(sifre.getText());

            if (this.sifreee == null) {

                this.sifreee = new Sifre();
                this.sifreee.setP_ad(adi);
                this.sifreee.setP_soyad(soyadi);
                this.sifreee.setKullanici_ad(kullanici);
                this.sifreee.setSifre(sifree);
                sifreManager.eklesifre(this.sifreee);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Hata Oluştu", "Hata", JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_kaydetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kaydet;
    private javax.swing.JTextField kullaniciadi;
    private javax.swing.JTextField pAdi;
    private javax.swing.JTextField pSoyadi;
    private javax.swing.JTextField sifre;
    // End of variables declaration//GEN-END:variables
}
