package proje.staj.forms;

import java.awt.GridLayout;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import proje.staj.db.Ogrenci;
import proje.staj.db.Staj;
import proje.staj.managers.OgrenciManager;
import proje.staj.managers.StajManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Zeynepnida
 */
public class StajDurum extends javax.swing.JPanel {
    /**
     * Creates new form staj_durum
     */
    public StajDurum() throws SQLException {
        initComponents();
        ((DefaultComboBoxModel) this.cmbOgrenci.getModel()).removeAllElements();

        ArrayList<Staj> stajList = new StajManager().getAllOgrenci();
        for (Staj staj : stajList) {
            ((DefaultComboBoxModel) this.cmbOgrenci.getModel()).addElement(staj);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbOgrenci = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTakvim = new javax.swing.JPanel();

        jLabel1.setText("Öğrenci :");

        cmbOgrenci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOgrenciActionPerformed(evt);
            }
        });

        pnlTakvim.setBackground(new java.awt.Color(204, 204, 255));
        pnlTakvim.setLayout(new java.awt.GridLayout(3, 5));
        jScrollPane1.setViewportView(pnlTakvim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(756, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbOgrenci, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOgrenciActionPerformed
         if(this.cmbOgrenci.getSelectedItem()!=null
                &&
                this.cmbOgrenci.getSelectedItem() instanceof Staj
                ){
        SimpleDateFormat dtFrm=new SimpleDateFormat("dd.MM.yyyy");
        Staj selectedStaj=(Staj) this.cmbOgrenci.getSelectedItem();
        Date baslamaTarihi=selectedStaj.getBaslama_tarihi();
        Date bitisTarihi=selectedStaj.getBitis_tarihi();
        long fark=bitisTarihi.getTime()-baslamaTarihi.getTime();
        long farkGun=fark/(1000*60*60*24);
        Calendar cl=Calendar.getInstance();
        cl.setTime(baslamaTarihi); 
         Calendar cl2=Calendar.getInstance();
        cl2.setTime(bitisTarihi);
        cl2.add(Calendar.DAY_OF_MONTH,1);
        int columnCount=7;
        int rowCount=(int) Math.round((farkGun/columnCount)+0.4)+1;
        this.pnlTakvim.setLayout(new GridLayout(rowCount, columnCount, 0,0));
        this.pnlTakvim.removeAll();
        this.pnlTakvim.invalidate();
        this.pnlTakvim.updateUI();
         cl.add(Calendar.DAY_OF_MONTH,-1);
        for(int i=0; i<columnCount*rowCount; i++){
           cl.add(Calendar.DAY_OF_MONTH,1);
            if(cl.getTime().before(cl2.getTime()) && cl.get(Calendar.DAY_OF_WEEK)!=Calendar.SATURDAY
                   &&
                   cl.get(Calendar.DAY_OF_WEEK)!=Calendar.SUNDAY){
            this.pnlTakvim.add(new TakipForm(cl.getTime(),selectedStaj));
           }else{
               this.pnlTakvim.add(new JPanel());
           }
        }
        this.pnlTakvim.invalidate();
        this.pnlTakvim.updateUI();
        }
    }//GEN-LAST:event_cmbOgrenciActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOgrenci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTakvim;
    // End of variables declaration//GEN-END:variables
}
