/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje.staj.forms;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import proje.staj.db.Devam;
import proje.staj.db.Staj;
import proje.staj.managers.DevamManager;

/**
 *
 * @author Zeynepnida
 */
public class TakipForm extends javax.swing.JPanel {

    private Devam devam;
    private Date dt;
    private Staj selectedStaj;

    /**
     * Creates new form TakipForm
     */

    TakipForm(Date time, Staj selectedStaj) {
        initComponents();
        this.selectedStaj = selectedStaj;
        SimpleDateFormat dtFrm = new SimpleDateFormat("dd.MM.yyyy");
        this.dt = time;

        LabelTarih.setText(dtFrm.format(time));

        if ((new DevamManager()).getDurum(time, selectedStaj)) {
            //gelmiştir
            kontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/tik.png")));
        } else {
            //gelmemiştir
            kontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/carpi.png")));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTarih = new javax.swing.JLabel();
        btnGeldi = new javax.swing.JButton();
        btnGelmedi = new javax.swing.JButton();
        kontrol = new javax.swing.JLabel();

        btnGeldi.setText("Geldi");
        btnGeldi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeldiActionPerformed(evt);
            }
        });

        btnGelmedi.setText("Gelmedi");
        btnGelmedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGelmediActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnGeldi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnGelmedi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(LabelTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGeldi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGelmedi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeldiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeldiActionPerformed

        DevamManager devamMan = new DevamManager();

        try {
            this.devam = new Devam();
            devam.setTarih(this.dt);
            devam.setDurum('E');
            devam.setStaj(this.selectedStaj);

            devamMan.geldi(this.devam);
 kontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/tik.png")));
        } catch (SQLException ex) {
            Logger.getLogger(TakipForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGeldiActionPerformed

    private void btnGelmediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGelmediActionPerformed

        DevamManager devamMan = new DevamManager();

        try {
            this.devam = new Devam();
            devam.setTarih(this.dt);
            devam.setDurum('H');
            devam.setStaj(this.selectedStaj);
            devamMan.gelmedi(this.devam);
 kontrol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/carpi.png")));
        } catch (SQLException ex) {
            Logger.getLogger(TakipForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGelmediActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTarih;
    private javax.swing.JButton btnGeldi;
    private javax.swing.JButton btnGelmedi;
    private javax.swing.JLabel kontrol;
    // End of variables declaration//GEN-END:variables
}
